### PR TITLE
Remove photo url

### PR DESCRIPTION
**Pull request by ARPspoofing**

### CODE REVIEW

**Comment by ARPspoofing** [comment]
I removed the need to add a valid photo image because I feel it is a feature flaw.

The mapping will instead be done internally to simulate retrieving the student's profile from some NUS database

**Comment by ARPspoofing** [comment]
@ShiJiaAo here are what I have changed: 

- Change the images from url to icons stored (because I feel it is a feature flaw for TA to add photos of students since they do not have access to it)
- Remove PREFIX_PHOTO in methods since TA will no longer use it
- Added attachments to events
- Added dates to events
- Added display of student profile in events when you add students e.g: addStudent 1 Tutorial/Dijkstra (you implemented it, I added the listing of students)
- The command to add attachment and dates example: touch Tutorial/Dijkstra -date dd/MM/yyyy -file FULL_FILE_PATH
- When you click on the event card (I will change the click to a command tmr,) the file attachments will open if it is valid
- Changed some test cases
- Changed prefix of performance from /per to /score

**Review by ShiJiaAo — APPROVED** [review]
Generally LGTM! Wondering if we are going to add event time too in the future (not just date)

I agree that having a mandatory photo in the input seems like a feature flaw. Totally support removing it

**Comment by ARPspoofing** [comment]
@ShiJiaAo yeap I am about to add that in after finishing the DG.
Since the date display on the ui works, I think the time should be doable as well.
Thanks for the review!

**Pull request merged**
